name: Tests (Linux)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages and local install
        uses: actions/cache@v2
        with:
          key: ${{ matrix.python-version }}
          path: |
            ~/.cache/pip
            ~/.local/bin

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install gcc gfortran libspatialindex-dev
          python -m pip install pip --upgrade --disable-pip-version-check
          export INSTALL_PREFIX=$HOME/.local
          ./ci/mf2005/install.sh
          ./ci/mfnwt/install.sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pip install pytest flake8
          pip install -e .

      - name: Linting
        run: |
          flake8 --exit-zero

      - name: Run tests with required packages
        run: |
          pytest -v

      - name: Run tests with optional packages
        run: |
          pip install flopy netcdf4
          pytest -v
